name: build

on:
  release:
  workflow_dispatch:
  
jobs:
  build:
    strategy:
        matrix:
          # Include amd64 on all platforms.
          goos: [windows, freebsd, openbsd, linux, dragonfly, darwin]
          goarch: [amd64, 386]
          exclude:
            # Exclude i386 on darwin and dragonfly.
            - goarch: 386
              goos: dragonfly
            - goarch: 386
              goos: darwin
          include:
            # BEGIN Linux ARM 5 6 7
            - goos: linux
              goarch: arm
              goarm: 7
            - goos: linux
              goarch: arm
              goarm: 6
            - goos: linux
              goarch: arm
              goarm: 5
            # END Linux ARM 5 6 7
            # Windows ARM 7
            - goos: windows
              goarch: arm
              goarm: 7
            # BEGIN Other architectures
            - goos: darwin
              goarch: arm64
            - goos: linux
              goarch: arm64
            - goos: linux
              goarch: riscv64
            # BEGIN MIPS
            - goos: linux
              goarch: mips64
            - goos: linux
              goarch: mips64le
            - goos: linux
              goarch: mipsle
            - goos: linux
              goarch: mips
            # END MIPS
            # BEGIN Android
            - goos: android
              goarch: arm64
            # END Android
            # END Other architectures
        fail-fast: false
        
    runs-on: ubuntu-latest
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      GOARM: ${{ matrix.goarm }}
      CGO_ENABLED: 0
      
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16.4
      
    - name: Handle for Non-Windows Build
      if: ${{ env.GOOS != 'windows' }}
      run: yes | cp ./windows/kernel32.go.nonwindows ./windows/kernel32.go
      
    - name: Build
      run: go build -v -o ZBProxy-${{ matrix.goos }}-${{ matrix.goarch }}-${{ matrix.goarm }}

    - name: Upload a Non-Windows Build Artifact
      uses: actions/upload-artifact@v2.2.4
      if: ${{ env.GOOS != 'windows' }}
      with:
        name: ZBProxy-${{ matrix.goos }}-${{ matrix.goarch }}-${{ matrix.goarm }}
        path: ZBProxy-${{ matrix.goos }}-${{ matrix.goarch }}-${{ matrix.goarm }}
        
    - name: Upload a Windows Build Artifact
      uses: actions/upload-artifact@v2.2.4
      if: ${{ env.GOOS == 'windows' }}
      with:
        name: ZBProxy-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goarm }}.exe
        path: ZBProxy-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goarm }}
